version: '3'
services:

  # The Application
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: my-app
    container_name: laravel-base-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../my-laravel-app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-base-network

  # The Web Server
  webserver:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: laravel-base-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../my-laravel-app:/var/www

    networks:
      - laravel-base-network

  # The Database
  db:
    image: mariadb:10.5
    container_name: laravel-base-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
     - laravel-base-network

networks:
  laravel-base-network:
    driver: bridge